package digen

import (
	"bytes"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/gymfony/di"
)

func TestParser_Parse_Scenarios(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatalf("failed to get working dir: %v", err)
	}
	diRootPath := filepath.Dir(wd)

	tests := []struct {
		name         string
		goModContent string
		files        map[string]string
		useEmptyPath bool
		wantErr      bool
		errSubstring string
		assertGraph  func(t *testing.T, graph *di.DependencyGraph)
	}{
		{
			name:         "Success with valid dependencies",
			goModContent: fmt.Sprintf("module testprog\ngo 1.22\nrequire github.com/gymfony/di v0.0.0\nreplace github.com/gymfony/di => %s", diRootPath),
			files: map[string]string{
				"main.go": `package main
import "github.com/gymfony/di"
type Mailer struct{}
func NewMailer() *Mailer { return &Mailer{} }
var Services = di.NewSet(NewMailer)
`,
			},
			wantErr: false,
		},
		{
			name:         "Skip generated files",
			goModContent: fmt.Sprintf("module testskip\ngo 1.22\nrequire github.com/gymfony/di v0.0.0\nreplace github.com/gymfony/di => %s", diRootPath),
			files: map[string]string{
				"gen.go": `// Code generated by digen. DO NOT EDIT.
package main
import "github.com/gymfony/di"
type GeneratedService struct{}
func NewGen() *GeneratedService { return &GeneratedService{} }
var Services = di.NewSet(NewGen)
`,
			},
			wantErr: false,
		},
		{
			name:         "Package syntax error parsing",
			goModContent: fmt.Sprintf("module testerr\ngo 1.22\nrequire github.com/gymfony/di v0.0.0\nreplace github.com/gymfony/di => %s", diRootPath),
			files: map[string]string{
				"main.go": `package main
this is a brutal broken syntax error
`,
			},
			wantErr:      true,
			errSubstring: "digen: Errors in package",
		},
		{
			name:         "Warning when argument type cannot be determined",
			goModContent: fmt.Sprintf("module testwarn\ngo 1.22\nrequire github.com/gymfony/di v0.0.0\nreplace github.com/gymfony/di => %s", diRootPath),
			files: map[string]string{
				"main.go": `package main
import "github.com/gymfony/di"
type Mailer struct{}
func NewMailer() *Mailer { return &Mailer{} }
var Services = di.NewSet(NewMailer, varWithoutType)
var varWithoutType = 123
`,
			},
			wantErr: false,
		},
		{
			name:         "Error when constructor returns no values",
			goModContent: fmt.Sprintf("module testerrvoid\ngo 1.22\nrequire github.com/gymfony/di v0.0.0\nreplace github.com/gymfony/di => %s", diRootPath),
			files: map[string]string{
				"main.go": `package main
import "github.com/gymfony/di"
func NewVoid() {}
var Services = di.NewSet(NewVoid)
`,
			},
			wantErr: false,
		},
		{
			name:         "Trigger logInfo with empty package list",
			goModContent: "module testempty\ngo 1.22",
			files:        map[string]string{},
			wantErr:      false,
		},
		{
			name:         "Error when path is empty",
			useEmptyPath: true,
			wantErr:      true,
			errSubstring: "project path cannot be empty",
		},
		{
			name:         "Success with di.Tag extraction",
			goModContent: fmt.Sprintf("module testtags\ngo 1.22\nrequire github.com/gymfony/di v0.0.0\nreplace github.com/gymfony/di => %s", diRootPath),
			files: map[string]string{
				"main.go": `package main
import "github.com/gymfony/di"

type Plugin interface {
	Init()
}

type MyPlugin struct{}
func (p *MyPlugin) Init() {}

func NewPlugin() *MyPlugin { return &MyPlugin{} }

type App struct {
	Plugins []Plugin
}

func NewApp(plugins []Plugin) *App { return &App{Plugins: plugins} }

var PluginTag = di.NewTagKey[Plugin]("plugins")

var Services = di.NewSet(
	di.Tag(NewPlugin, PluginTag),
	NewApp,
)
`,
			},
			wantErr: false,
			assertGraph: func(t *testing.T, graph *di.DependencyGraph) {
				// 1. Проверяем, что узел плагина распарсился корректно, несмотря на обёртку di.Tag
				pluginNode, exists := graph.Nodes["*testtags.MyPlugin"]
				if !exists {
					t.Fatalf("expected node '*testtags.MyPlugin' to exist in graph")
				}
				if pluginNode.CtorName != "NewPlugin" {
					t.Errorf("expected CtorName 'NewPlugin', got %q", pluginNode.CtorName)
				}

				// Проверяем, что дженерик-тип тега успешно извлёкся в слайс Tags
				if len(pluginNode.Tags) != 1 || pluginNode.Tags[0] != "testtags.Plugin" {
					t.Errorf("expected tags [\"testtags.Plugin\"], got %v", pluginNode.Tags)
				}

				// 2. Проверяем узел приложения, который зависит от слайса интерфейсов
				appNode, exists := graph.Nodes["*testtags.App"]
				if !exists {
					t.Fatalf("expected node '*testtags.App' to exist in graph")
				}
				if len(appNode.Deps) != 1 || appNode.Deps[0] != "[]testtags.Plugin" {
					t.Errorf("expected dependencies [\"[]testtags.Plugin\"], got %v", appNode.Deps)
				}
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tmpDir := t.TempDir()

			if tt.goModContent != "" {
				_ = os.WriteFile(filepath.Join(tmpDir, "go.mod"), []byte(tt.goModContent), 0o644)
			}

			for filename, content := range tt.files {
				_ = os.WriteFile(filepath.Join(tmpDir, filename), []byte(content), 0o644)
			}

			if tt.goModContent != "" && !tt.wantErr {
				cmd := exec.Command("go", "mod", "tidy")
				cmd.Dir = tmpDir
				cmd.Env = append(os.Environ(), "GOPROXY=off", "GO111MODULE=on")
				_ = cmd.Run()
			}

			var buf bytes.Buffer
			log := slog.New(slog.NewTextHandler(&buf, &slog.HandlerOptions{Level: slog.LevelDebug}))
			parser := NewParser(log)

			targetPath := tmpDir
			if tt.useEmptyPath {
				targetPath = ""
			}

			graph, err := parser.Parse(targetPath)

			if (err != nil) != tt.wantErr {
				t.Fatalf("Parser.Parse() error = %v, wantErr %v", err, tt.wantErr)
			}

			if tt.wantErr && tt.errSubstring != "" {
				if !strings.Contains(err.Error(), tt.errSubstring) {
					t.Errorf("expected error containing %q, got %q", tt.errSubstring, err.Error())
				}
			}

			if !tt.wantErr && tt.assertGraph != nil {
				tt.assertGraph(t, graph)
			}

			if buf.Len() > 0 {
				t.Log(buf.String())
			}
		})
	}
}

func TestParser_New_NilSafety(t *testing.T) {
	parser := NewParser(nil)
	if parser.log == nil {
		t.Error("expected default discard logger when passing nil, got nil")
	}
}
