package digen

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/gymfony/di"
)

type mockLogger struct{ t *testing.T }

func (m *mockLogger) Debug(msg string, args ...any) { m.t.Logf("[DEBUG] "+msg, args...) }
func (m *mockLogger) Info(msg string, args ...any)  { m.t.Logf("[INFO] "+msg, args...) }
func (m *mockLogger) Warn(msg string, args ...any)  { m.t.Logf("[WARN] "+msg, args...) }
func (m *mockLogger) Error(msg string, args ...any) { m.t.Logf("[ERROR] "+msg, args...) }

func TestParser_Parse_Scenarios(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatalf("failed to get working dir: %v", err)
	}
	diRootPath := filepath.Dir(wd)

	// We describe the structure of test cases
	tests := []struct {
		name          string
		goModContent  string
		files         map[string]string
		args          []string
		wantErr       bool
		errSubstring  string
		validateGraph func(t *testing.T, graph interface{}) // simple assertion of internal structure
	}{
		{
			name:         "Success with valid dependencies",
			goModContent: fmt.Sprintf("module testprog\ngo 1.22\nrequire github.com/gymfony/di v0.0.0\nreplace github.com/gymfony/di => %s", diRootPath),
			files: map[string]string{
				"main.go": `package main
import "github.com/gymfony/di"
type Mailer struct{}
func NewMailer() *Mailer { return &Mailer{} }
var Services = di.NewSet(NewMailer)
`,
			},
			args:    []string{"-project-path", "TMP_DIR"},
			wantErr: false,
		},
		{
			name:         "Skip generated files",
			goModContent: fmt.Sprintf("module testskip\ngo 1.22\nrequire github.com/gymfony/di v0.0.0\nreplace github.com/gymfony/di => %s", diRootPath),
			files: map[string]string{
				"gen.go": `// Code generated by digen. DO NOT EDIT.
package main
import "github.com/gymfony/di"
type GeneratedService struct{}
func NewGen() *GeneratedService { return &GeneratedService{} }
var Services = di.NewSet(NewGen)
`,
			},
			args:    []string{"-project-path", "TMP_DIR"},
			wantErr: false,
			validateGraph: func(t *testing.T, g interface{}) {
				// Check that the graph remains empty since the file is skipped
				if len(g.(*di.DependencyGraph).Nodes) != 0 {
					t.Errorf("expected 0 nodes because generated file should be skipped")
				}
			},
		},
		{
			name:         "Package syntax error parsing",
			goModContent: fmt.Sprintf("module testerr\ngo 1.22\nrequire github.com/gymfony/di v0.0.0\nreplace github.com/gymfony/di => %s", diRootPath),
			files: map[string]string{
				"main.go": `package main
this is a brutal broken syntax error
`,
			},
			args:         []string{"-project-path", "TMP_DIR"},
			wantErr:      true,
			errSubstring: "digen: Errors in package",
		},
		{
			name:         "Invalid CLI flags format",
			goModContent: "module testflags\ngo 1.22",
			files:        map[string]string{"main.go": "package main"},
			args:         []string{"-unsupported-flag-name=xyz"},
			wantErr:      true,
			errSubstring: "digen: failed to parse flags",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tmpDir := t.TempDir()

			// Create go.mod if it is defined
			if tt.goModContent != "" {
				_ = os.WriteFile(filepath.Join(tmpDir, "go.mod"), []byte(tt.goModContent), 0o644)
			}

			// Create test files
			for filename, content := range tt.files {
				_ = os.WriteFile(filepath.Join(tmpDir, filename), []byte(content), 0o644)
			}

			// Replace the TMP_DIR marker in the arguments with the real path
			runArgs := make([]string, len(tt.args))
			for i, arg := range tt.args {
				if arg == "TMP_DIR" {
					runArgs[i] = tmpDir
				} else {
					runArgs[i] = arg
				}
			}

			// Run go mod tidy only for cases without syntax errors and flags,
			// to save time, and only if go.mod is present
			if tt.goModContent != "" && !strings.Contains(tt.name, "Invalid CLI flags") && !tt.wantErr {
				cmd := exec.Command("go", "mod", "tidy")
				cmd.Dir = tmpDir
				cmd.Env = append(os.Environ(), "GOPROXY=off", "GO111MODULE=on")
				_ = cmd.Run()
			}

			logger := NewParserLogger(&mockLogger{t: t})
			parser := NewParser(logger)

			graph, err := parser.Parse(runArgs)

			if (err != nil) != tt.wantErr {
				t.Fatalf("Parser.Parse() error = %v, wantErr %v", err, tt.wantErr)
			}

			if tt.wantErr && tt.errSubstring != "" {
				if !strings.Contains(err.Error(), tt.errSubstring) {
					t.Errorf("expected error containing %q, got %q", tt.errSubstring, err.Error())
				}
			}

			if !tt.wantErr && tt.validateGraph != nil {
				tt.validateGraph(t, graph)
			}
		})
	}
}

func TestParser_Parse_EmptyPath(t *testing.T) {
	logger := NewParserLogger(&mockLogger{t: t})
	parser := NewParser(logger)

	args := []string{"-project-path", ""}
	_, err := parser.Parse(args)

	if err == nil {
		t.Error("expected error when project path is empty, got nil")
	}
}

// Test for a logger without a real recipient (testing the nil-safe branch)
func TestParserLogger_NilSafety(t *testing.T) {
	var nilLogger *ParserLogger
	// Не должно падать по panic
	nilLogger.logDebug("test")
	nilLogger.logInfo("test")
	nilLogger.logWarn("test")
	nilLogger.logError("test")

	emptyLogger := NewParserLogger(nil)
	emptyLogger.logDebug("test")
	emptyLogger.logInfo("test")
	emptyLogger.logWarn("test")
	emptyLogger.logError("test")
}
